os: linux
language: shell
services: docker
install: sudo apt-get -y install jq curl

env:
  global:
    - REPO=${DOCKER_USERNAME}/alpine-base
    - VERSION=${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT::8}
  jobs:
    - ARCH=amd64
    - ARCH=aarch64
    - ARCH=armhf

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

stage: "Build"
script:
  - docker build --build-arg ARCH=${ARCH} --tag $REPO:${ARCH}-${VERSION} .
  - if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then docker push $REPO:${ARCH}-${VERSION} ; fi
  - docker tag $REPO:${ARCH}-${VERSION} $REPO:${ARCH}-latest
  - docker push $REPO:${ARCH}-latest

jobs:
  include:
    - stage: "Deploy"
      name: "Manifest"
      script:
        - cat <<< $(jq '.+{"experimental":"enabled"}' ~/.docker/config.json) > ~/.docker/config.json
        - |
          push() {
            docker pull $REPO:amd64-${1} & docker pull $REPO:aarch64-${1} & docker pull $REPO:armhf-${1}
            docker manifest create $REPO:${1} $REPO:amd64-${1} $REPO:aarch64-${1} $REPO:armhf-${1}
            docker manifest annotate $REPO:${1} $REPO:amd64-${1} --os linux --arch amd64
            docker manifest annotate $REPO:${1} $REPO:armhf-${1} --os linux --arch arm --variant v7
            docker manifest annotate $REPO:${1} $REPO:aarch64-${1} --os linux --arch arm64 --variant v8
            docker manifest push --purge $REPO:${1}
          }
        - if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then push ${VERSION} ; fi
        - push latest
